{% set name = "django-elasticsearch-dsl" %}
{% set version = "7.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-elasticsearch-dsl-{{ version }}.tar.gz
  sha256: 265812e22538899333ebb8622c2b9d053eb4e1e44b24c09730da67c90103a6b3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - elasticsearch-dsl >=7.2.0
    - django >=1.9.6
    - python >=3.6
    - six

test:
  imports:
    - django_elasticsearch_dsl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/django-es/django-elasticsearch-dsl
  summary: Wrapper around elasticsearch-dsl-py for django models
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
